In [ ]:
# !pip install pythainlp

In [ ]:

# !wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS' -O Fastfood_Opinion.csv

# Logistic Regression

In [ ]:
import pandas as pd
import numpy as np
from pythainlp.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Step 1: Load and preprocess the data
data = pd.read_csv('Fastfood_Opinion.csv')  # Replace 'your_dataset.csv' with the path to your dataset
X = data['message'].astype(str)  # Text data in the 'message' column
y = data['class']  # Labels in the 'class' column


# Step 2: Create bag-of-words representation
# Preprocess the data Before training the model, you need to preprocess the Thai text data to convert it into tokenized
# and numerical features. We'll use scikit-learn's CountVectorizer to transform the text data into bag-of-word features (bow).

# Tokenize Thai text
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

vectorizer = CountVectorizer(analyzer=lambda x: x)  # Use the list of tokens as the analyzer
X_bow = vectorizer.fit_transform(X_tokenized)
print(X_bow.shape) # (documents, vocab)

vocab = np.array(vectorizer.get_feature_names_out())
print(vocab.shape)
print(vocab[250:270])


(642, 3549)
(3549,)
['Motorway' 'Mushroom' 'Nugget' 'Operation' 'Order' 'PM' 'POS' 'Paradise'
 'Park' 'Piroj' 'Pizza' 'Place' 'Plaza' 'Pork' 'QR' 'Qhappy' 'Qr' 'Rayong'
 'Refill' 'Riverside']


In [ ]:
print(X_tokenized[2])
print(X_bow[2])
print(vocab[1021])
print(vocab[1069])

['Burger', 'King', 'สาขา', 'The', 'Bright', 'พระราม', '2', 'บริการ', 'ห่วย', 'มาก', 'ถึง', 'มาก', 'ที่สุด', 'วันนี้', 'ไป', 'ทาน', 'กับ', 'ลูก', '3', 'คน', 'พนักงาน', 'รับ', 'ออเดอร์', 'มัวแต่', 'คุย', 'เล่น', 'กัน', 'ยืน', 'กัน', 'หลาย', 'คน', 'แต่', 'เปิด', 'เคา', 'เตอร์', 'เดียว', 'กว่า', 'จะ', 'สั่ง', 'ได้', 'นาน', 'มาก', 'พอ', 'สั่ง', 'แล้ว', 'เฟรนฟ', 'ราย', 'หมด', 'พอดี', 'พนักงาน', 'บอ', 'กว่า', 'เดี๋ยว', 'เอา', 'ไป', 'ให้', 'ที่', 'โต๊ะ', 'ก็', 'ไม่เป็นไร', 'ก็', 'ไป', 'นั่ง', 'รอ', 'ก็', 'นั่ง', 'ป้อน', 'แฮมเบอร์เกอร์', 'ลูก', 'ๆ', 'ไป', 'ซัก', 'พักใหญ่', 'เฟรนฟ', 'ราย', 'ก็', 'ยัง', 'ไม่', 'มา', 'แต่', 'เห็น', 'โต๊ะ', 'อื่น', 'ที่มา', 'หลัง', 'เรา', 'ได้', 'แล้ว', 'ก็', 'ลุก', 'ไป', 'ตาม', 'กับ', 'ผู้จัดการ', '(', 'แต่งตัว', 'ไม่', 'เหมือน', 'คนอื่น', ')', 'ตาม', 'ครั้ง', 'ที่', '1', 'ก็', 'ได้รับ', 'คำตอบ', 'เหมือนเดิม', 'ไป', 'นั่ง', 'รอ', 'ที่', 'โต๊ะ', 'เดี๋ยว', 'ไป', 'เส', 'ริ', 'ฟ', 'ให้', 'จน', 'ป้อน', 'เด็ก', 'จน', 'หมด', 'ใช้เวลา', 'ประมาณ', '30', 'นาที', 'ก็', 'เดิน

In [ ]:
# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial logistic regression
logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = logreg_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8992248062015504


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.86      0.91        74
           1       0.84      0.95      0.89        55

    accuracy                           0.90       129
   macro avg       0.90      0.91      0.90       129
weighted avg       0.91      0.90      0.90       129

Confusion Matrix:
[[64 10]
 [ 3 52]]


In [ ]:
# Predict New Data: Example 1
## *** ให้นิสิตแก้ไข code เพื่อให้ส่งข้อมูลตัดคำไปทำ vectorizer ได้ถูกต้อง และจะทำให้ classify ได้ถูกต้อง

#new_text = "ของไม่ตรงปก ส่งช้า แพ็คไม่ดี"
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = logreg_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 51)	1
  (0, 555)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1585)	1
  (0, 1881)	1
  (0, 1882)	1
  (0, 3209)	1
  (0, 3441)	1
predict :  [1]


In [ ]:
# Predict New Data: Example 2

new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = logreg_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 150)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1957)	1
  (0, 2575)	1
  (0, 3209)	1
  (0, 3412)	1
  (0, 3441)	1
  (0, 3493)	1
predict :  [1]


# Naive Bays

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

from pythainlp.tokenize import word_tokenize

# Step 1: Load and preprocess the data
data = pd.read_csv('Fastfood_Opinion.csv')  # Replace 'your_dataset.csv' with the path to your dataset
X = data['message'].astype(str)  # Text data in the 'message' column
y = data['class']  # Labels in the 'class' column

# Tokenize Thai text
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

# Step 2: Create bag-of-words representation
vectorizer2 = CountVectorizer(analyzer=lambda x: x)  # Use the list of tokens as the analyzer
X_bow = vectorizer2.fit_transform(X_tokenized)
print(X_bow.shape) # (documents, vocab)

# Step 3: Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

# Step 4: Train the binomial Naive Bayes classifier
nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


(642, 3549)
Accuracy: 0.8914728682170543


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.96      0.91        74
           1       0.94      0.80      0.86        55

    accuracy                           0.89       129
   macro avg       0.90      0.88      0.89       129
weighted avg       0.90      0.89      0.89       129

Confusion Matrix:
[[71  3]
 [11 44]]


In [ ]:
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer2.transform([new_text_tokenized])
print(new_text_bow)

y_pred = nb_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 51)	1
  (0, 555)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1585)	1
  (0, 1881)	1
  (0, 1882)	1
  (0, 3209)	1
  (0, 3441)	1
predict :  [0]


In [ ]:
new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer2.transform([new_text_tokenized])
print(new_text_bow)

y_pred = nb_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 150)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1957)	1
  (0, 2575)	1
  (0, 3209)	1
  (0, 3412)	1
  (0, 3441)	1
  (0, 3493)	1
predict :  [0]


# DecisionTree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

# Step 1: Load and preprocess the data
data = pd.read_csv('Fastfood_Opinion.csv')  # Replace 'your_dataset.csv' with the path to your dataset
X = data['message'].astype(str)  # Text data in the 'message' column
y = data['class']  # Labels in the 'class' column

# Tokenize Thai text
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

# Step 2: Create bag-of-words representation
vectorizer3 = CountVectorizer(analyzer=lambda x: x)  # Use the list of tokens as the analyzer
X_bow = vectorizer3.fit_transform(X_tokenized)
print(X_bow.shape) # (documents, vocab)

data = pd.read_csv('Fastfood_Opinion.csv')
X = data['message'].astype(str)
y = data['class']

X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)
clf = DecisionTreeClassifier()
# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


(642, 3549)
Accuracy: 0.875968992248062


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        74
           1       0.85      0.85      0.85        55

    accuracy                           0.88       129
   macro avg       0.87      0.87      0.87       129
weighted avg       0.88      0.88      0.88       129

Confusion Matrix:
[[66  8]
 [ 8 47]]


In [ ]:
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer3.transform([new_text_tokenized])
print(new_text_bow)

y_pred = clf.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 51)	1
  (0, 555)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1585)	1
  (0, 1881)	1
  (0, 1882)	1
  (0, 3209)	1
  (0, 3441)	1
predict :  [1]


In [ ]:
new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer3.transform([new_text_tokenized])
print(new_text_bow)

y_pred = clf.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 150)	1
  (0, 1038)	1
  (0, 1426)	1
  (0, 1957)	1
  (0, 2575)	1
  (0, 3209)	1
  (0, 3412)	1
  (0, 3441)	1
  (0, 3493)	1
predict :  [0]


# TF-IDF

# Logistic Regression

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [ ]:
data = pd.read_csv('Fastfood_Opinion.csv')
X = data['message'].astype(str)
y = data['class']

In [ ]:
X_tokenized = X.apply(word_tokenize, keep_whitespace=False)
vectorizer = TfidfVectorizer(analyzer=lambda x: x)
X_bow = vectorizer.fit_transform(X_tokenized)
print(X_bow.shape)
vocab = np.array(vectorizer.get_feature_names_out())
print(vocab.shape)
print(vocab[3500:3510])

(642, 3549)
(3549,)
['ไม่เท่าไหร่' 'ไม่เป็นไร' 'ไม้' 'ไร' 'ไร้' 'ไลน์' 'ไล่' 'ไล่ออก' 'ไว'
 'ไว้']


In [ ]:
print(X_tokenized[0])
print(X_bow[0])

['11.30', 'น.', 'ไป', 'ที่', 'สาขา', 'ใน', 'ปั๊ม', 'คาลเท็กซ์', 'ประ', 'ชานุ', 'กู', 'ล', 'ซื้อ', 'พาย', 'ไก่', 'และ', 'พาย', 'เผือก', 'อย่าง', 'ละ', '2', 'ชิ้น', 'กลับ', 'ถึง', 'บ้าน', 'จะ', 'ทาน', 'พาย', 'ไก่', 'เปิด', 'มา', 'กลายเป็น', 'พาย', 'เชอรี่', 'ทั้งสอง', 'ชิ้น', 'เลย', 'แย่จัง']
  (0, 3280)	0.19967979047201942
  (0, 3034)	0.057450836701905275
  (0, 1300)	0.17924460163754558
  (0, 2773)	0.19967979047201942
  (0, 495)	0.1672907824742227
  (0, 1881)	0.05473795894025931
  (0, 2913)	0.1099219545165859
  (0, 1315)	0.0738016565088901
  (0, 857)	0.0646577478188027
  (0, 1590)	0.11210678689789609
  (0, 1242)	0.09615330121272804
  (0, 485)	0.11287258957964276
  (0, 948)	0.23775008436136766
  (0, 109)	0.09659664408741996
  (0, 2154)	0.11529711226976311
  (0, 2584)	0.1059852159708011
  (0, 2942)	0.1672907824742227
  (0, 3291)	0.08235182841801443
  (0, 3453)	0.2458959106262061
  (0, 1772)	0.6089230055717042
  (0, 1006)	0.11615171545717369
  (0, 2135)	0.14231096251438263
  (0, 570)	0.155

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

logreg_classifier = LogisticRegression()
logreg_classifier.fit(X_train, y_train)

y_pred = logreg_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9069767441860465


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.92        74
           1       0.92      0.85      0.89        55

    accuracy                           0.91       129
   macro avg       0.91      0.90      0.90       129
weighted avg       0.91      0.91      0.91       129

Confusion Matrix:
[[70  4]
 [ 8 47]]


In [ ]:
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = logreg_classifier.predict(new_text_bow)
print('predict : ',y_pred)


  (0, 3441)	0.2443973805947284
  (0, 3209)	0.239151800824748
  (0, 1882)	0.2073723113408591
  (0, 1881)	0.19961658506184696
  (0, 1585)	0.4406797805644825
  (0, 1426)	0.32380755278152207
  (0, 1038)	0.5449029992881355
  (0, 555)	0.26989192991037647
  (0, 51)	0.36251254775171565
predict :  [1]


In [ ]:
new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = logreg_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 3493)	0.1648582280481312
  (0, 3441)	0.22766686294079466
  (0, 3412)	0.3783049103099124
  (0, 3209)	0.22278037566490402
  (0, 2575)	0.2993384439208498
  (0, 1957)	0.30641101376191476
  (0, 1426)	0.30164091594971476
  (0, 1038)	0.507601006823703
  (0, 150)	0.44283927733497297
predict :  [0]


# Naive Bays

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

data = pd.read_csv('Fastfood_Opinion.csv')
X = data['message'].astype(str)
y = data['class']

X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

vectorizer2 = TfidfVectorizer(analyzer=lambda x: x)
X_bow = vectorizer2.fit_transform(X_tokenized)
print(X_bow.shape)

X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

nb_classifier = MultinomialNB()
nb_classifier.fit(X_train, y_train)

y_pred = nb_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


(642, 3549)
Accuracy: 0.8527131782945736


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        74
           1       1.00      0.65      0.79        55

    accuracy                           0.85       129
   macro avg       0.90      0.83      0.84       129
weighted avg       0.88      0.85      0.85       129

Confusion Matrix:
[[74  0]
 [19 36]]


In [ ]:
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = nb_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 3441)	0.2443973805947284
  (0, 3209)	0.239151800824748
  (0, 1882)	0.2073723113408591
  (0, 1881)	0.19961658506184696
  (0, 1585)	0.4406797805644825
  (0, 1426)	0.32380755278152207
  (0, 1038)	0.5449029992881355
  (0, 555)	0.26989192991037647
  (0, 51)	0.36251254775171565
predict :  [0]


In [ ]:
new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = nb_classifier.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 3493)	0.1648582280481312
  (0, 3441)	0.22766686294079466
  (0, 3412)	0.3783049103099124
  (0, 3209)	0.22278037566490402
  (0, 2575)	0.2993384439208498
  (0, 1957)	0.30641101376191476
  (0, 1426)	0.30164091594971476
  (0, 1038)	0.507601006823703
  (0, 150)	0.44283927733497297
predict :  [0]


# DecisionTree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree

data = pd.read_csv('Fastfood_Opinion.csv')
X = data['message'].astype(str)
y = data['class']

X_tokenized = X.apply(word_tokenize, keep_whitespace=False)

vectorizer3 = TfidfVectorizer(analyzer=lambda x: x)
X_bow = vectorizer3.fit_transform(X_tokenized)
print(X_bow.shape)

X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier()
clf = clf.fit(X_train,y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

(642, 3549)
Accuracy: 0.7751937984496124


In [ ]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.77      0.80        74
           1       0.72      0.78      0.75        55

    accuracy                           0.78       129
   macro avg       0.77      0.78      0.77       129
weighted avg       0.78      0.78      0.78       129

Confusion Matrix:
[[57 17]
 [12 43]]


In [ ]:
new_text = "มากินบ่อยมาก แต่ให้ 1 ดาวนะ"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = clf.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 3441)	0.2443973805947284
  (0, 3209)	0.239151800824748
  (0, 1882)	0.2073723113408591
  (0, 1881)	0.19961658506184696
  (0, 1585)	0.4406797805644825
  (0, 1426)	0.32380755278152207
  (0, 1038)	0.5449029992881355
  (0, 555)	0.26989192991037647
  (0, 51)	0.36251254775171565
predict :  [1]


In [ ]:
new_text = "อยากให้ 5 ดาวนะแต่ยังไม่ใช่"
new_text_tokenized = word_tokenize(new_text , keep_whitespace=False)
new_text_bow = vectorizer.transform([new_text_tokenized])
print(new_text_bow)

y_pred = clf.predict(new_text_bow)
print('predict : ',y_pred)

  (0, 3493)	0.1648582280481312
  (0, 3441)	0.22766686294079466
  (0, 3412)	0.3783049103099124
  (0, 3209)	0.22278037566490402
  (0, 2575)	0.2993384439208498
  (0, 1957)	0.30641101376191476
  (0, 1426)	0.30164091594971476
  (0, 1038)	0.507601006823703
  (0, 150)	0.44283927733497297
predict :  [0]
