In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install pythainlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 21.2 MB/s eta 0:00:00


In [ ]:
# !pip install tensorflow transformers

# data cleanning

In [ ]:
import re
from pythainlp.corpus import thai_stopwords
from pythainlp.tokenize import word_tokenize
import pandas as pd
import numpy as np
from keras.utils import pad_sequences
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Dense, Embedding,Flatten,SimpleRNN,LSTM,Bidirectional
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import seaborn as sns

In [ ]:
data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/#พรรคก้าวไกล.xlsx')
data.head()

labels                                               text
0  negative  พรรคปัญญาอ่อนจะใช้อ.ชูศักดิ์ ศิรินิลสส. เพื่อไ...
1  negative  ลอรี่ พงศ์พล ผู้สมัคร สส จาก รทสช บอก ก้าวไกล ...
2  negative  ถาม นิด บอกว่าขอศึกษาก่อน ใจเย็นนิดนึง อ้าว!!ต...
3  negative  เพื่อไทยกำลังจะใช้ประเด็นนี้ดิสเครดิต ก้าวไกล ...
4  negative  เพื่อไทย จะร่วมมือกับขั้วอำนาจเก่าจัดการกับ ก้...

In [ ]:
def convert_labels_to_binary(label):
    if label == "positive":
        return 2
    elif label == "negative":
        return 1
    elif label == "neutral":
        return 0
labels = data.iloc[:,0]
labels = [convert_labels_to_binary(label) for label in labels]
labels

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,


In [ ]:
print("Unique lables = " , set(labels))
y=to_categorical([ int(i) for i in labels])
print(y)

Unique lables =  {0, 1, 2}
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 

In [ ]:
format = r"[\u0E00-\u0E7Fa-zA-Z ' 0-9]+"
stop_word = list(thai_stopwords())+[" ","\n"]

def tokenize(sentence):
    return word_tokenize(sentence,engine="newmm")
def cleanning_emoji(tk):
    return [re.findall(format,text)[0] for text in tk if re.findall(format,text)]
def cleanning_stop_word(tk):
    return [word for word in tk if word not in stop_word]
def big_cleanning(sentence):
    return cleanning_emoji(tokenize(sentence))

message = [big_cleanning(sentence) for sentence in data["text"].values]
message[0:5]

[['พรรค',
  'ปัญญาอ่อน',
  'จะ',
  'ใช้',
  'อ',
  'ชู',
  'ศักดิ์',
  ' ',
  'ศิ',
  'ริ',
  'นิล',
  'สส',
  ' ',
  'เพื่อ',
  'ไทย',
  ' ',
  'ตีความ',
  'บทบัญญัติ',
  'กฎหมาย',
  'เอาผิด',
  ' ',
  'ก้าวไกล',
  ' ',
  'และ',
  ' ',
  'หมอ',
  'อ๋อง',
  ' ',
  'ขู่',
  'ถึงขั้น',
  'ยุบ',
  'พรรค',
  ' ',
  '55555555',
  ' ',
  'ตกลง',
  'มึง',
  'ไม่',
  'แก้',
  'แล้ว',
  'ใช่',
  'มั้ย',
  'รธน',
  ' ',
  'กู',
  'เริ่ม',
  'ไม่',
  'แน่ใจ',
  'แล้ว',
  'ว่า',
  'ตอนนี้',
  'พรรคก้าวไกล',
  'หรือ',
  'รัฐธรรมนูญ',
  '60',
  'ที่',
  'เป็นปัญหา',
  'สำหรับ',
  ' ',
  'พรรคเพื่อไทย',
  ' ',
  'มากกว่า',
  'กัน'],
 ['ลอ',
  'รี่',
  ' ',
  'พงศ์',
  'พล',
  ' ',
  'ผู้สมัคร',
  ' ',
  'สส',
  ' ',
  'จาก',
  ' ',
  'รท',
  'สช',
  ' ',
  'บอก',
  ' ',
  'ก้าวไกล',
  ' ',
  'โกง',
  'เก้าอี้',
  ' ',
  'ประธาน',
  ' ',
  'กม',
  'ธ',
  ' ',
  'บอก',
  'พรรค',
  'ที่',
  'ต่อต้าน',
  'สืบทอด',
  'อำ',
  'นาน',
  ' ',
  'กลับ',
  'หวง',
  'อำนาจ',
  'เสีย',
  'เอง',
  ' ',
  'ลอ',
  '

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(message)
tts = tokenizer.texts_to_sequences(message)
max_length = max([len(s) for s in tts])
print("max sentense's length = " , max_length)
X = pad_sequences(tts, maxlen=max_length, padding="post")
print("Sequence Padding at maxlen words, post padding:\n", X)
vocab_size = len(tokenizer.word_index) +1
print("vocab size : ",vocab_size)

max sentense's length =  668
Sequence Padding at maxlen words, post padding:
 [[   9 1119    6 ...    0    0    0]
 [ 528  731    1 ...    0    0    0]
 [ 111    1 1135 ...    0    0    0]
 ...
 [  39 2327 2328 ...    0    0    0]
 [1118    1 2333 ...    0    0    0]
 [  20    1   92 ...    0    0    0]]
vocab size :  2347


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.15,random_state = 42)

In [ ]:
type(y)

numpy.ndarray

In [ ]:
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1

# Train

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=128, input_length=max_length) )
model.add(Bidirectional(LSTM(64)))
model.add(Dense(32, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=[ 'accuracy' ])
model.fit(X_train, y_train, epochs=10, batch_size=64, validation_split=0.1)

loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test Loss: {loss* 100:.2f}")
print(f"Test Accuracy: {accuracy* 100:.2f}")

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 668, 128)          300416    
                                                                 
 bidirectional (Bidirection  (None, 128)               98816     
 al)                                                             
                                                                 
 dense (Dense)               (None, 32)                4128      
                                                                 
 dense_1 (Dense)             (None, 12)                396       
                                                                 
 dense_2 (Dense)             (None, 3)                 39        
                                                                 
Total params: 403795 (1.54 MB)
Trainable params: 403795 (1.54 MB)
Non-trainable params: 0 (0.00 Byte)
____________________

KeyboardInterrupt: ignored

In [ ]:
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true_classes = np.argmax(y_test, axis=1)

confusion_mtx = confusion_matrix(y_pred_classes,y_true_classes)

plt.figure(figsize=(8, 6))
sns.heatmap(confusion_mtx, annot=True, fmt='d', cmap='Blues', xticklabels=['Class 0', 'Class 1', 'Class 2'], yticklabels=['Class 0', 'Class 1', 'Class 2'])
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

In [ ]:
text = "แย่"
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
tts = tokenizer.texts_to_sequences([text])
max_length = max([len(s) for s in tts])
X = pad_sequences(tts, maxlen=max_length, padding="post")
y_pred = model.predict(X)
y_pred_classes = np.argmax(y_pred, axis=1)
y_pred_classes