In [ ]:
!pip install pythainlp

In [ ]:
!wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS' -O FastFood_Opinion.csv

--2024-12-16 09:01:35--  https://docs.google.com/uc?export=download&id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS
Resolving docs.google.com (docs.google.com)... 142.251.16.101, 142.251.16.139, 142.251.16.102, ...
Connecting to docs.google.com (docs.google.com)|142.251.16.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS&export=download [following]
--2024-12-16 09:01:35--  https://drive.usercontent.google.com/download?id=1K0VgdwYagNidu5k_y5pnSrGrGIOBPsyS&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.163.132, 2607:f8b0:4004:c1b::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.163.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 348315 (340K) [application/octet-stream]
Saving to: ‘FastFood_Opinion.csv’

FastFood_Opinion.cs 100%[===================>] 340.15K  --.-KB

In [ ]:
import pandas as pd
import numpy as np
from pythainlp.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

df = pd.read_csv('FastFood_Opinion.csv')
df.head()

class                                            message
0      0  11.30 น. ไปที่สาขาในปั๊มคาลเท็กซ์ ประชานุกูล ซ...
1      0  BK ทุกสาขาบริการดี โดยเฉพาะอย่างยิ่งเอมโพเรียม...
2      0  Burger King สาขา The Bright พระราม 2 บริการห่ว...
3      0  Burger King สาขาปั้ม ป.ต.ท.บ้านพร อ.ถลาง เมื่อ...
4      0  chicken strip ชิ้นเล็กมาก เทียบกับป้ายโฆษณาบนโต๊ะ

In [ ]:
X = df['message'].astype(str)
y = df['class']
X_tokenized = X.apply(lambda x: word_tokenize(x, engine='longest', keep_whitespace=False))
X_tokenized

0      [11.30, น., ไป, ที่, สาขา, ใน, ปั๊ม, คาลเท็กซ์...
1      [bk, ทุก, สาขา, บริการ, ดี, โดยเฉพาะอย่างยิ่ง,...
2      [burger, king, สาขา, the, bright, พระราม, 2, บ...
3      [burger, king, สา, ขา, ปั้ม, ป., ต., ท., บ้าน,...
4      [chicken, strip, ชิ้น, เล็ก, มาก, เทียบ, กับ, ...
                             ...                        
637                 [ช่วง, โปรฯ, คุณภาพ, เกิน, ราคา, คะ]
638              [อร่อย, มาก, ราคา, โอ, เค, ร, เลย, ค่ะ]
639                              [อาหาร, อร่อย, มาก, คะ]
640            [คุณภาพ, และ, การ, บริการ, ระดับ, 5, ดาว]
641                            [อาหาร, อร่อย, มากๆ, ค่ะ]
Name: message, Length: 642, dtype: object

# Logistic Regression

## term frequency

In [ ]:
vectorizer = CountVectorizer(analyzer=lambda x: x)
X_bow = vectorizer.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

logis = LogisticRegression()
logis.fit(X_train, y_train)

y_pred = logis.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9069767441860465

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer.transform(new_text_tokenized)

logis.predict(new_text_bow)

array([0, 0])

## one hot

In [ ]:
vectorizer_oh = CountVectorizer(analyzer=lambda x: x,binary=True)
X_bow = vectorizer_oh.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

logis_oh = LogisticRegression()
logis_oh.fit(X_train, y_train)

y_pred = logis_oh.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9147286821705426

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer_oh.transform(new_text_tokenized)

logis_oh.predict(new_text_bow)

array([0, 0])

## TF-IDF

In [ ]:
vectorizer_tfidf = TfidfVectorizer(analyzer=lambda x: x)
X_bow = vectorizer_tfidf.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

logis_tfidf = LogisticRegression()
logis_tfidf.fit(X_train, y_train)

y_pred = logis_tfidf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9069767441860465

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer_tfidf.transform(new_text_tokenized)

logis_tfidf.predict(new_text_bow)

array([0, 0])

# Naive Bayes

## term frequency

In [ ]:
vectorizer = CountVectorizer(analyzer=lambda x: x)
X_bow = vectorizer.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

nb = MultinomialNB()
nb.fit(X_train, y_train)

y_pred = nb.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9069767441860465

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer.transform(new_text_tokenized)

nb.predict(new_text_bow)

array([0, 0])

## one hot

In [ ]:
vectorizer_oh = CountVectorizer(analyzer=lambda x: x,binary=True)
X_bow = vectorizer_oh.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

nb_oh = MultinomialNB()
nb_oh.fit(X_train, y_train)

y_pred = nb_oh.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8914728682170543

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer_oh.transform(new_text_tokenized)

nb_oh.predict(new_text_bow)

array([0, 0])

## TF-IDF

In [ ]:
vectorizer_tfidf = TfidfVectorizer(analyzer=lambda x: x)
X_bow = vectorizer_tfidf.fit_transform(X_tokenized)
X_train, X_test, y_train, y_test = train_test_split(X_bow, y, test_size=0.2, random_state=42)

nb_tfidf = LogisticRegression()
nb_tfidf.fit(X_train, y_train)

y_pred = nb_tfidf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9069767441860465

In [ ]:
new_text = ["ไม่แย่ ดี","ไม่ดี แย่"]
new_text_tokenized = [word_tokenize(text, engine='longest', keep_whitespace=False) for text in new_text]
new_text_bow = vectorizer_tfidf.transform(new_text_tokenized)

nb_tfidf.predict(new_text_bow)

array([0, 0])